SET SCHEMA FN71839;

CREATE TABLE CLIENTS(
  TELEPHONE_NUMBER VARCHAR(13) NOT NULL CONSTRAINT PK_CLIENT_TEL PRIMARY KEY,
  CLIENT_NAME VARCHAR(50),
  PAYMENT CHAR(7) CHECK (PAYMENT IN('BY CARD', 'IN CASH')),
  BRANCH_NAME VARCHAR(20)
);

CREATE TABLE ORDERS(
    ORDER_NUMBER INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1)
        CONSTRAINT PK_ORDER_NUM PRIMARY KEY,
    ORDER_PRICE DOUBLE CHECK(ORDER_PRICE > 0),
    ORDER_DATE DATE,
    CLIENT_TELEPHONE VARCHAR(13) CHECK(CLIENT_TELEPHONE NOT LIKE '%[0-9]%')
);

CREATE TABLE BRANCHES(
    BRANCH_NAME VARCHAR(20) NOT NULL CONSTRAINT PK_BRANCH_NAME PRIMARY KEY ,
    MONTHLY_TURNOVER DOUBLE CHECK (MONTHLY_TURNOVER > 0),
    MNGR_ID INT,
    MNGR_START_DATE DATE
);

CREATE TABLE EMPLOYEES(
    EMPL_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1)
                      CONSTRAINT PK_EMP_ID PRIMARY KEY ,
    EGN VARCHAR(10) CHECK(EGN  NOT LIKE '%[0-9]%'),
    EMPLOYEE_NAME VARCHAR(50),
    SALARY DOUBLE CHECK(SALARY>0),
    SEX CHAR(1) CHECK(SEX IN('M', 'F')),
    BRANCH_NAME VARCHAR(20) CONSTRAINT FK_BRANCH_EMP REFERENCES BRANCHES(BRANCH_NAME)
);

CREATE TABLE SUPPLIERS(
    COMPANY VARCHAR(20) NOT NULL CONSTRAINT PK_SUPL_COMP PRIMARY KEY,
    NAME VARCHAR(50)
);

CREATE TABLE ITEMS(
    ITEM_NUMBER INT NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 100 INCREMENT BY 1)
                  CONSTRAINT PK_ITEM_NUM PRIMARY KEY,
    PRICE DOUBLE CHECK(PRICE>0),
    NAME VARCHAR(20) NOT NULL
);

CREATE TABLE SUPPLIES(
    BRANCH_NAME VARCHAR(20) NOT NULL,
    COMPANY_NAME VARCHAR(30) NOT NULL,
    DELIVERY_PRICE DOUBLE CHECK(DELIVERY_PRICE > 0),
    PRIMARY KEY (BRANCH_NAME, COMPANY_NAME)
);

CREATE TABLE ORDER_DETAILS(
    ORDER_NUM INT NOT NULL ,
    ITEM_NUM INT NOT NULL,
    QUANTITY INT,
    CONSTRAINT PK_ORD_DET PRIMARY KEY (ORDER_NUM, ITEM_NUM)
);

ALTER TABLE CLIENTS
ADD CHECK(TELEPHONE_NUMBER NOT LIKE '%[0-9]%');

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORD_CLIENT FOREIGN KEY (CLIENT_TELEPHONE) REFERENCES CLIENTS(TELEPHONE_NUMBER);

ALTER TABLE CLIENTS
ADD CONSTRAINT FK_BRANCH_CLIENT FOREIGN KEY(BRANCH_NAME) REFERENCES BRANCHES(BRANCH_NAME);

ALTER TABLE SUPPLIES
ADD CONSTRAINT FK_SUP_BRANCH FOREIGN KEY(BRANCH_NAME) REFERENCES BRANCHES(BRANCH_NAME);

ALTER TABLE SUPPLIES
ADD CONSTRAINT FK_SUP_COMPANY FOREIGN KEY(COMPANY_NAME) REFERENCES SUPPLIERS(COMPANY);

ALTER TABLE ORDER_DETAILS
ADD CONSTRAINT FK_ORD_NUM FOREIGN KEY(ORDER_NUM) REFERENCES ORDERS(ORDER_NUMBER);

ALTER TABLE ORDER_DETAILS
ADD CONSTRAINT FK_ITEM_NUM FOREIGN KEY(ITEM_NUM) REFERENCES ITEMS(ITEM_NUMBER);

ALTER TABLE BRANCHES
ADD CONSTRAINT FK_MNG_ID FOREIGN KEY (MNGR_ID) REFERENCES EMPLOYEES(EMPL_ID);